# Reference to some URL from clipboard
matches:
  # Markdown reference to some URL from clipboard:
  - trigger: ":mdref"
    replace: "[{{label}}]({{clipboard}})"
    vars:
      - name: clipboard
        type: clipboard
      - name: label
        type: shell
        params:
          cmd: "${CONFIG}/scripts/label_for_url ${ESPANSO_CLIPBOARD}"
          trim: true
  # AsciiDoc-formatted reference to some URL from clipboard
  - trigger: ":adref"
    replace: "link:{{clipboard}}[{{label}}]"
    vars:
      - name: clipboard
        type: clipboard
      - name: label
        type: shell
        params:
          cmd: "${CONFIG}/scripts/label_for_url ${ESPANSO_CLIPBOARD}"
          trim: true
  # Jira-formatted reference to some URL from clipboard
  - trigger: ":jiraref"
    replace: "[{{label}}|{{clipboard}}]"
    vars:
      - name: clipboard
        type: clipboard
      - name: label
        type: shell
        params:
          cmd: "${CONFIG}/scripts/label_for_url ${ESPANSO_CLIPBOARD}"
          trim: true
  # "Rich" reference to some URL from clipboard
  - trigger: ":ref"
    markdown: "[{{label}}]({{clipboard}})"
    vars:
      - name: clipboard
        type: clipboard
      - name: label
        type: shell
        params:
          cmd: "${CONFIG}/scripts/label_for_url ${ESPANSO_CLIPBOARD}"
          trim: true
